#!/usr/bin/env python3
"""
lab-runner — the ONLY place uploaded strategies are executed.

Deployed with: no network (network_mode: none), no secrets, read-only market data (/data:ro),
read-only root filesystem, non-root user, CPU/memory limits. Each job additionally runs in a
subprocess with an empty environment, resource limits and a timeout.

Loop: /sandbox/queue/<id>.job → register in importer registry → write port → check → test → status.
"""
import json
import os
import re
import resource
import subprocess
import sys
import time
from pathlib import Path

import store

DATA_RO = Path(os.getenv("MARKET_DATA_DIR", "/data"))
IMPORTER = os.getenv("IMPORTER", "/app/importer/import_tool.py")
INTAKE_DIR = str(Path(__file__).resolve().parent)
BACKTEST_DIR = os.getenv("BACKTEST_DIR", "/app/backtest")
TEST_TIMEOUT = int(os.getenv("LAB_TEST_TIMEOUT", "1800"))
LANG = {"pine": "pine", "mql4": "mql4", "mql5": "mql5", "python": "python", "paper": "paper"}

WRAPPER = '''"""Auto-generated by lab-runner from an uploaded file — compiled from {spec}, no free code."""
import json
import sys
from pathlib import Path

sys.path.insert(0, {intake!r})
from spec import compile_spec

STRATEGY = compile_spec(json.loads(Path(__file__).with_suffix(".spec.json").read_text()))
'''


def limits():
    os.setsid()
    resource.setrlimit(resource.RLIMIT_AS, (3 * 1024 ** 3, 3 * 1024 ** 3))
    resource.setrlimit(resource.RLIMIT_CPU, (TEST_TIMEOUT, TEST_TIMEOUT))
    resource.setrlimit(resource.RLIMIT_FSIZE, (512 * 1024 ** 2, 512 * 1024 ** 2))
    resource.setrlimit(resource.RLIMIT_CORE, (0, 0))


def run_tool(*args, timeout=600):
    env = {"PATH": "/usr/local/bin:/usr/bin:/bin", "DATA_DIR": str(store.SANDBOX), "HOME": "/tmp",
           "PYTHONPATH": f"{INTAKE_DIR}:{BACKTEST_DIR}", "PYTHONDONTWRITEBYTECODE": "1", "MPLCONFIGDIR": "/tmp"}
    p = subprocess.run([sys.executable, "-I", IMPORTER, *args], env=env, cwd="/tmp", capture_output=True, text=True,
                       timeout=timeout, preexec_fn=limits)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def registry_events(name):
    reg = store.SANDBOX / "imports" / "registry.jsonl"
    if not reg.exists():
        return []
    return [r for r in (json.loads(l) for l in reg.read_text().splitlines() if l.strip()) if r.get("name") == name]


def setup():
    store.SANDBOX.mkdir(parents=True, exist_ok=True)
    link = store.SANDBOX / "parquet"
    if not link.exists():
        link.symlink_to(DATA_RO / "parquet")
    (store.SANDBOX / "imports" / "strategies").mkdir(parents=True, exist_ok=True)
    (store.SANDBOX / "reports").mkdir(parents=True, exist_ok=True)


def import_name(st):
    base = re.sub(r"[^a-z0-9_]+", "_", (st.get("name") or "upload").lower()).strip("_")[:32] or "upload"
    if not base[0].isalpha():
        base = "u_" + base
    return f"{base}_{st['id'][-6:]}"


def process(sid):
    st = store.load(sid)
    if not st or st.get("state") in store.TERMINAL:
        return
    d = store.sdir(sid)
    name = import_name(st)
    st["import_name"] = name
    store.advance(st, "checking")

    url = st.get("url") or f"upload://{st['filename']}"
    args = ["register", "--name", name, "--url", url, "--source", st.get("source") or "other",
            "--lang", LANG.get(st.get("lang"), "paper" if st.get("kind") == "pdf" else "text"),
            "--original", str(d / st["stored_as"])]
    if st.get("license"):
        args += ["--license", st["license"]]
    if st.get("claim"):
        args += ["--claim", st["claim"]]
    rc, out = run_tool(*args)
    if rc != 0:
        store.advance(st, "failed", error="تعذّر تسجيل الاستراتيجية: " + out.strip()[-300:])
        return

    port = store.SANDBOX / "imports" / "strategies" / f"{name}.py"
    if (d / "spec.json").exists():
        port.with_suffix(".spec.json").write_text((d / "spec.json").read_text())
        port.write_text(WRAPPER.format(spec=st["filename"], intake=INTAKE_DIR))
    elif (d / "port.py").exists():
        port.write_text((d / "port.py").read_text())
    else:
        store.advance(st, "failed", error="لا توجد مواصفة أو كود للاختبار")
        return

    try:
        rc, out = run_tool("check", "--name", name, timeout=900)
    except subprocess.TimeoutExpired:
        store.advance(st, "failed", error="انتهت مهلة الفحص")
        return
    chk = [r for r in registry_events(name) if r["event"] == "CHECK"]
    if not chk:
        store.advance(st, "failed", error="فشل الفحص: " + out.strip()[-400:])
        return
    st["check_flags"] = chk[-1].get("flags", [])
    if chk[-1]["status"] == "BLOCKED":
        why = "، ".join(f["why"] for f in st["check_flags"] if f["severity"] == "BLOCK")
        store.advance(st, "blocked", error=why or "محظورة في الفحص")
        return

    store.advance(st, "testing")
    try:
        rc, out = run_tool("test", "--name", name, timeout=TEST_TIMEOUT)
    except subprocess.TimeoutExpired:
        store.advance(st, "failed", error=f"انتهت مهلة الاختبار ({TEST_TIMEOUT // 60} دقيقة)")
        return
    tested = [r for r in registry_events(name) if r["event"] == "TESTED"]
    if rc != 0 or not tested:
        store.advance(st, "failed", error="فشل الاختبار: " + out.strip()[-400:])
        return
    t = tested[-1]
    results = []
    try:
        import pandas as pd
        res = pd.read_csv(Path(t["report"]) / "results.csv")
        cols = ["pair", "verdict", "wf_sharpe", "wf_profit_factor", "wf_max_dd_pct", "wf_trades", "wf_cagr_pct",
                "stress_sharpe", "is_sharpe", "reasons"]
        res = res[[c for c in cols if c in res.columns]].astype(object).where(pd.notna(res), None)
        results = res.to_dict("records")
    except Exception:
        pass
    store.advance(st, "done", verdict=t["verdict"], pairs_passed=t.get("pairs_passed", []),
                  pairs_tested=t.get("pairs_tested"), best_wf_sharpe=t.get("best_wf_sharpe"),
                  report=Path(t["report"]).name, results=results)


def main():
    setup()
    once = "--once" in sys.argv
    print("lab-runner ready", flush=True)
    while True:
        jobs = sorted(store.QUEUE.glob("*.job")) if store.QUEUE.exists() else []
        for job in jobs:
            sid = job.stem
            try:
                process(sid)
            except Exception as e:
                st = store.load(sid)
                if st:
                    store.advance(st, "failed", error=f"خطأ في المشغّل: {type(e).__name__}: {e}")
            finally:
                job.unlink(missing_ok=True)
        if once:
            return
        time.sleep(5)


if __name__ == "__main__":
    main()
